### PR TITLE
Implement task Search algorithms

### PR DESCRIPTION
**Pull request by snguyenthanh**
- Change how basic search executes
- Add advanced search feature
- Create the dropping-all-function function in `information_schema`.

@karrui Can you help adding the UI for advanced search ?
> Notes:
> * All the parameters of the advanced search function are in `TEXT`.
> * Add a DatePicker for `start_dt` (not __DateTimePicker__).
> * Strip out all white spaces in inputs for `category_id`, `min_price` and `max_price`.
> * If any user inputs are empty strings, leave them as empty strings.
#### Example for Advanced Search queries:
1. Select all tasks:
    * `SELECT get_tasks_with_advanced_search('', '', '', '', '', '', '', '', '');`
2. Select tasks with `search_string = 'data'`:
    * `SELECT get_tasks_with_advanced_search('data', '', '', '', '', '', '', '', '');`
3. Select tasks with `search_string = 'data'` and `min_price = 20`:
    * `SELECT get_tasks_with_advanced_search('data', '', '', '', '', '', '20', '', '');`

### CODE REVIEW

**Comment by karrui** [comment]
I added the implementation of advanced search.
- Reposition search bar to navbar instead of only in the task page
- Add advanced search page


**Bugs found:**
- Search by location doesn't seem to work
- Search by user seems to have unintended behaviour; I search for user "karrui" it returns user "test" and vice versa

**Comment by snguyenthanh** [comment]
* Bugs for searching by `location` and `user` have been resolved by fixing the functionality bug of function `get_matching_pattern`.
* Bug for searching `requester` has been fixed by setting a default value of `requester` if null.

@karrui please have a final check.

**Comment by karrui** [comment]
Made date formatting better, not so painful to read the dates anymore. Everything else seems good now, good to merge.

**Comment by snguyenthanh** [comment]
Add a check for `task.location` contains the full string of user-input `location`

**Pull request merged**
